test:
	go test ./...
integration:
	go test -tags=integration ./...
forcetest:
	go clean -testcache && go test ./...
forceintegration:
	go clean -testcache && go test -tags=integration ./...
coverage:
	go clean -testcache && go test -cover ./...
build:
	go build -ldflags="-X 'main.Version=$(version)'" -o cotton .